apiVersion: v1
kind: Service
metadata:
  name: gallery-jwt-service
  namespace: art
  labels:
    run: gallery-jwt-service
spec:
  type: ClusterIP
  ports:
  - port: 3333
    targetPort: http-jwt-api
  selector:
    app: gallery