apiVersion: v1
kind: Service
metadata:
  name: gallery-pictures-service
  labels:
    run: gallery-pictures-service
spec:
  type: NodePort
  ports:
  - port: 8889
    protocol: TCP
    targetPort: 8888
  selector:
    app: gallery