apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-jwt-deploy
  namespace: art
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - image: gallery-jwt:v1
        name: gallery-jwt
        imagePullPolicy: Never
        ports:
        - containerPort: 3333
          name: http-jwt-api
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
