apiVersion: v1
kind: Service
metadata:
  name: gallery-jwt-service
  labels:
    run: gallery-jwt-service
spec:
  type: NodePort
  ports:
  - port: 3334
    protocol: TCP
    targetPort: 3333
  selector:
    app: gallery