apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-mysql8-deploy
  namespace: art
  labels:
    app: gallery
spec:
  selector:
    matchLabels:
      app: gallery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - image: gallery-mysql:v1
        name: gallery-mysql-8
        imagePullPolicy: Never
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
          name: gallery
