apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-mysql
  namespace: art
  labels:
    app: gallery-mysql
spec:
  selector:
    matchLabels:
      app: gallery-mysql
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gallery-mysql
    spec:
      containers:
      - image: gallery-mysql:v1
        name: gallery-mysql
        imagePullPolicy: Never
        args: ["--default-authentication-plugin=mysql_native_password"]
        ports:
        - containerPort: 3306
          name: gallery-mysql
