apiVersion: v1
kind: Service
metadata:
  name: gallery-admin
  namespace: art
  labels:
    app: gallery-admin
spec:
  type: NodePort
  ports:
  - port: 4000
    nodePort: 32600
    protocol: TCP
    targetPort: 4000
  selector:
    app: gallery-admin