apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-scripts
  namespace: art
  labels:
    app: gallery-scripts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery-scripts
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gallery-scripts
    spec:
      containers:
      - image: gallery-scripts:v1
        name: gallery-scripts
        imagePullPolicy: Never
        ports:
        - containerPort: 2000
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
