apiVersion: v1
kind: Service
metadata:
  name: gallery-scripts
  namespace: art
  labels:
    app: gallery-scripts
spec:
  type: NodePort
  ports:
  - port: 2000
    nodePort: 32626
    protocol: TCP
    targetPort: 2000
  selector:
    app: gallery-scripts