apiVersion: v1
kind: Service
metadata:
  name: gallery-images
  namespace: art
  labels:
    app: gallery-images
spec:
  type: NodePort
  ports:
  - port: 8888
    nodePort: 30050
    protocol: TCP
    targetPort: 8888
  selector:
    app: gallery-images
  sessionAffinity: None