apiVersion: apps/v1
kind: Deployment
metadata:
  name: gallery-admin-deploy
  namespace: art
  labels:
    app: gallery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gallery
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gallery
    spec:
      containers:
      - image: gallery-admin:v1
        name: gallery-admin
        env:
        - name: MYSQL_HOST_CONTAINER
          value: "gallery-mysql8-service"
        - name: MYSQL_PORT_CONTAINER
          value: "6601"
        - name: JWT_SERVICE_HOST_CONTAINER
          value: "gallery-jwt-service"
        - name: JWT_SERVICE_PORT_CONTAINER
          value: "3333"
        - name: IMAGES_SERVICE_HOST_CONTAINER
          value: "192.168.99.101"
        - name: IMAGES_SERVICE_PORT_CONTAINER
          value: "30050"
        - name: SCRIPTS_SERVICE_HOST_CONTAINER
          value: "192.168.99.101"
        - name: SCRIPTS_SERVICE_PORT_CONTAINER
          value: "32626"
        - name: APP_SERVICE_HOST_CONTAINER
          value: "192.168.99.101"
        - name: APP_SERVICE_PORT_CONTAINER
          value: "32260"
        - name: JWT_URI
          value: "http://gallery-jwt-service.art.svc.cluster.local:3333"
        imagePullPolicy: Never
        ports:
        - containerPort: 4000
        resources:
          requests:
            memory: "128M"
            cpu: 500m
