/* TODO: DB.categories */
const categories = [
    {"id":1, "path":"realism", "name":"Realism"},
    {"id":2, "path":"hyperrealism", "name":"Hyperrealism"},
    {"id":3, "path":"surrealism", "name":"Surrealism"},
    {"id":4, "path":"impressionism", "name":"Impressionism"},
    {"id":5, "path":"expressionism", "name":"Expressionism"},
    {"id":6, "path":"abstract-art", "name":"Abstract art"},
    {"id":7, "path":"pop-art", "name":"Pop Art"},
    {"id":8, "path":"cubism", "name":"Cubism"},
    {"id":9, "path":"portrait", "name":"Portrait"},
    {"id":10, "path":"gender-painting", "name":"Gender painting"},
    {"id":11, "path":"landscape", "name":"Landscape"},
    {"id":12, "path":"still-life", "name":"Still life"},
    {"id":13, "path":"naked", "name":"Naked"},
    {"id":14, "path":"historical-painting", "name":"Historical Painting"},
    {"id":15, "path":"oil", "name":"Oil"},
    {"id":16, "path":"wax", "name":"Wax"},
    {"id":17, "path":"watercolor", "name":"Watercolor"},
    {"id":18, "path":"tempera", "name":"Tempera"},
    {"id":19, "path":"acrylic", "name":"Acrylic"},
    {"id":20, "path":"pie", "name":"Pie"},
    {"id":21, "path":"quenching", "name":"Quenching"},
    {"id":22, "path":"ink", "name":"Ink"},
    {"id":23, "path":"cool", "name":"Cool"},
    {"id":24, "path":"grisalea", "name":"Grisalea"},
    {"id":25, "path":"pointillism", "name":"Pointillism"},
    {"id":26, "path":"dripping", "name":"Dripping"},
    {"id":27, "path":"graffiti", "name":"Graffiti"},
    {"id":28, "path":"mixed-media", "name":"Mixed media"},
    {"id":29, "path":"on-wooden-board", "name":"On wooden board"},
    {"id":30, "path":"on-canvas", "name":"On canvas"},
    {"id":31, "path":"in-copper", "name":"In copper"},
    {"id":32, "path":"in-glass", "name":"In glass"},
    {"id":33, "path":"on-paper", "name":"On paper"},
    {"id":34, "path":"sculpture", "name":"Sculpture"},
    {"id":35, "path":"abstract-sculpture", "name":"Abstract sculpture"},
    {"id":36, "path":"relief", "name":"Relief"},
    {"id":37, "path":"color-relief", "name":"Color relief"},
    {"id":38, "path":"glass-relief", "name":"Glass relief"},
    {"id":39, "path":"contemporary", "name":"Contemporary"},
    {"id":40, "path":"round-bulk-statue", "name":"Round Bulk Statue"},
    {"id":41, "path":"low-relief", "name":"Low relief"},
    {"id":42, "path":"bust", "name":"Bust"},
    {"id":43, "path":"torso", "name":"Torso"},
    {"id":44, "path":"kinetic-sculpture", "name":"Kinetic sculpture"},
    {"id":45, "path":"chryselephantine", "name":"Chryselephantine"},
    {"id":46, "path":"architectural-sculpture", "name":"Architectural sculpture"},
    {"id":47, "path":"clay-sculpture", "name":"Clay sculpture"},
    {"id":48, "path":"stone-sculpture", "name":"Stone sculpture"},
    {"id":49, "path":"stucco-sculpture", "name":"Stucco sculpture"},
    {"id":50, "path":"metal-sculpture", "name":"Metal sculpture"},
    {"id":51, "path":"wood-sculpture", "name":"Wood sculpture"},
    {"id":52, "path":"ivory-sculpture", "name":"Ivory Sculpture"},
    {"id":53, "path":"concrete-sculpture", "name":"Concrete sculpture"},
    {"id":54, "path":"emptying", "name":"Emptying"},
    {"id":55, "path":"removing", "name":"Removing"},
    {"id":56, "path":"adding", "name":"Adding"}
];

module.exports = categories;